server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:    
    gateway:      
      discovery:
        locator:
          enabled: true
      routes:
        - id: mscatalog
          uri: lb://catalog-service
          predicates:
            - Path=/api/v1/catalog/**

info:
  app:
    name: ${spring.application.name}

eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceURL:
         defaultZone: http://localhost:8761/eureka
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway
